name: master_calculator
description: "Master Bilingual Financial, Health and Utility Calculator."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  shared_preferences: ^2.3.0
  share_plus: ^9.0.0
  unity_ads_plugin: ^0.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: false
